---
title: Jamie Lord
timezone: Europe/London
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
    permalink: "/:collection/:name"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: single
    author_profile: true
    read_time: true
    comments: false
    share: true
    related: true
- scope:
    path: _pages
    type: pages
  values:
    layout: single
    author_profile: true
- scope:
    path: _projects
    type: projects
  values:
    layout: single
    author_profile: true
subtitle: Lord.technology
url: https://lord.technology
repository: jamie-lord/Lord.technology
email: jamie@lord.technology
description: Jamie Lord is a lead developer based in Nottingham, UK using C#, Vue.js,
  TypeScript and Azure technologies to build awesome products
twitter_username: jme_lord
github_username: jamie-lord
minimal_mistakes_skin: lord
search: true
locale: en-GB
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
permalink: "/:year/:month/:day/:title:output_ext"
paginate: 5
paginate_path: "/page:num/"
include:
- _pages
plugins:
- jekyll-remote-theme
- jekyll-paginate
- jekyll-sitemap
- jekyll-gist
- jekyll-feed
- jemoji
- jekyll-include-cache
- jekyll-seo-tag
author:
  name: Jamie Lord
  avatar: "/assets/images/jamie.jpg"
  bio: Lead developer using C#, Vue.js, TypeScript and Azure technologies to build
    awesome products
  location: Nottingham, UK
  links:
  - label: GitHub
    icon: fab fa-fw fa-github
    url: https://github.com/jamie-lord
  - label: Linkedin
    icon: fab fa-fw fa-linkedin
    url: https://www.linkedin.com/in/jamie-lord
  - label: Twitter
    icon: fab fa-fw fa-twitter-square
    url: https://twitter.com/jme_lord
social:
  type: Person
  name: Jamie Lord
  links:
  - https://github.com/jamie-lord
  - https://www.linkedin.com/in/jamie-lord
  - https://twitter.com/jme_lord
footer:
  links:
  - label: GitHub
    icon: fab fa-fw fa-github
    url: https://github.com/jamie-lord
  - label: Linkedin
    icon: fab fa-fw fa-linkedin
    url: https://www.linkedin.com/in/jamie-lord
  - label: Twitter
    icon: fab fa-fw fa-twitter-square
    url: https://twitter.com/jme_lord
category_archive:
  type: liquid
  path: "/categories/"
tag_archive:
  type: liquid
  path: "/tags/"
compress_html:
  clippings: all
  comments: all
  blanklines: true
  ignore:
    envs: development
